export const THEMES = {
  'minimal-elegance': {
    id: 'minimal-elegance',
    name: 'Minimal Elegance',
    description: 'Clean, white-space-heavy design with serif typography. Perfect for writers & designers.',
    preview: '/themes/minimal.png',
    colors: {
      primary: '#1a1a2e',
      accent: '#e94560',
      background: '#ffffff',
      surface: '#f8f9fa',
      text: '#2d2d2d',
    },
    font: 'Georgia, serif',
  },
  'developer-dark': {
    id: 'developer-dark',
    name: 'Developer Dark',
    description: 'Terminal-inspired dark theme with monospace fonts and gradient accents. For developers.',
    preview: '/themes/developer.png',
    colors: {
      primary: '#0a0a0f',
      accent: '#00d4aa',
      background: '#0d1117',
      surface: '#161b22',
      text: '#e6edf3',
    },
    font: '"JetBrains Mono", monospace',
  },
  'creative-studio': {
    id: 'creative-studio',
    name: 'Creative Studio',
    description: 'Bold colors, asymmetric grids, and large imagery. For photographers & artists.',
    preview: '/themes/creative.png',
    colors: {
      primary: '#ff6b35',
      accent: '#ffd166',
      background: '#1a1a2e',
      surface: '#22223b',
      text: '#edf2f4',
    },
    font: '"Outfit", sans-serif',
  },
  'corporate-pro': {
    id: 'corporate-pro',
    name: 'Corporate Professional',
    description: 'Sleek, structured, business-ready. For managers, consultants & executives.',
    preview: '/themes/corporate.png',
    colors: {
      primary: '#0f3460',
      accent: '#3a86ff',
      background: '#f0f4f8',
      surface: '#ffffff',
      text: '#1d3557',
    },
    font: '"Inter", sans-serif',
  },
  'glassmorphism-modern': {
    id: 'glassmorphism-modern',
    name: 'Glassmorphism Modern',
    description: 'Frosted glass cards, gradient backgrounds, floating elements. For modern creatives.',
    preview: '/themes/glass.png',
    colors: {
      primary: '#667eea',
      accent: '#764ba2',
      background: '#0c0c1d',
      surface: 'rgba(255,255,255,0.08)',
      text: '#f0f0f0',
    },
    font: '"Outfit", sans-serif',
  },
};

export const DEFAULT_SECTIONS_ORDER = [
  'hero',
  'about',
  'skills',
  'projects',
  'experience',
  'education',
  'testimonials',
  'contact',
];

export const SKILL_CATEGORIES = [
  'Frontend',
  'Backend',
  'DevOps',
  'Design',
  'Mobile',
  'Database',
  'Languages',
  'Tools',
  'Soft Skills',
  'Other',
];

export const DEFAULT_PORTFOLIO = {
  theme: 'minimal-elegance',
  accent_color: '#6C63FF',
  tagline: '',
  bio: '',
  profile_image: '',
  hero_title: '',
  hero_subtitle: '',
  cta_text: 'View My Work',
  cta_link: '#projects',
  about_text: '',
  about_image: '',
  resume_url: '',
  location: '',
  phone: '',
  website: '',
  linkedin: '',
  github: '',
  twitter: '',
  dribbble: '',
  behance: '',
  youtube: '',
  instagram: '',
  sections_order: DEFAULT_SECTIONS_ORDER,
  is_published: true,
};
